### ISSUE TITLE
Unable to call Xpress.createprob

### ISSUE THREAD

**Issue by NLaws** [jump-dev/Xpress.jl#128]
While [working on isolating a memory leak issue](https://discourse.julialang.org/t/memory-consumption-growth-with-many-large-milps-in-jump/61895) I first came across a [`prob not defined` issue](https://github.com/jump-dev/Xpress.jl/issues/125) that is now fixed in the master branch. Now I am getting the following traceback while looping over a series of Xpress problems (see run.jl defined at the end of the traceback):
```julia
ERROR: LoadError: XpressError(1): Bad input encountered. Unable to call `Xpress.createprob`:

(Unable to extract error message for Base.RefValue{Ptr{Nothing}}.).

Stacktrace:
  [1] macro expansion
    @ ~/.julia/packages/Xpress/ORUxc/src/utils.jl:137 [inlined]
  [2] createprob(_probholder::Base.RefValue{Ptr{Nothing}})
    @ Xpress ~/.julia/packages/Xpress/ORUxc/src/api.jl:56
  [3] Xpress.XpressProblem(; logfile::String)
    @ Xpress ~/.julia/packages/Xpress/ORUxc/src/helper.jl:71
  [4] XpressProblem
    @ ~/.julia/packages/Xpress/ORUxc/src/helper.jl:70 [inlined]
  [5] empty!(model::Xpress.Optimizer)
    @ Xpress ~/.julia/packages/Xpress/ORUxc/src/MOI/MOI_wrapper.jl:281
  [6] Xpress.Optimizer(; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Xpress ~/.julia/packages/Xpress/ORUxc/src/MOI/MOI_wrapper.jl:271
  [7] Optimizer
    @ ~/.julia/packages/Xpress/ORUxc/src/MOI/MOI_wrapper.jl:250 [inlined]
  [8] _instantiate_and_check(optimizer_constructor::Type{Xpress.Optimizer})
    @ MathOptInterface ~/.julia/packages/MathOptInterface/1EYfq/src/instantiate.jl:62
  [9] instantiate(optimizer_constructor::Type; with_bridge_type::Type{Float64}, with_names::Bool)
    @ MathOptInterface ~/.julia/packages/MathOptInterface/1EYfq/src/instantiate.jl:120
 [10] set_optimizer(model::Model, optimizer_constructor::Type; bridge_constraints::Bool)
    @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/optimizer_interface.jl:109
 [11] Model(optimizer_factory::Type; bridge_constraints::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/JuMP.jl:287
 [12] Model
    @ ~/.julia/packages/JuMP/Xrr7O/src/JuMP.jl:286 [inlined]
 [13] top-level scope
    @ /opt/solver/run.jl:4
in expression starting at /opt/solver/run.jl:3

# /opt/solver/run.jl
using REoptLite, JuMP, Xpress

for _ in range(1,stop=500)
    m = Model(Xpress.Optimizer)
    r = run_reopt(m, "outage.json")
    finalize(m)
end
```
I can provide the outage.json if anyone would like to recreate the issue (it has happened twice for me after running approximately 25-30 models/iterations.
The line that fails is `m = Model(Xpress.Optimizer)`.

Any ideas @kdheepak or @joaquimg ?

**Comment by kdheepak** [comment]
Does it happen consistently at the same number of iterations? Is your program deterministic? If not, can you make it so? i.e. use the same random seed etc.

**Comment by NLaws** [comment]
My program is deterministic and it does not happen consistently at the same number of iterations. I was not tracking the first two sets (hence the 25-30 estimate, which as based on time spent). So I ran a third set and it failed at iteration number 245.

**Comment by joaquimg** [comment]
Maybe a license limit? Or even memory?

**Comment by NLaws** [comment]
Definitely could be memory related, but if that were the issue I would think that instead of an error from Xpress.jl  that Docker would kill the container.  I don't know how it could be a license issue. I guess the `Bad input encountered.` is raised from FICO Xpress (not Xpress.jl)? That is weird given that the inputs are the same every iteration.

**Comment by joaquimg** [comment]
The string `Bad input encountered.` comes from the julia wrapper: https://github.com/jump-dev/Xpress.jl/blob/f15573f967a1e4f775e687c87ebf26e397b96118/src/helper.jl#L11
but it is raised when the C API returns `1`, which means "Bad input encountered." according to the manual.

Since all the problems are the same I recommend printing Xpress' internal representation of the problems before each solve and compare two runs. This might give you a hint of what is going on.
Use this function to print the in memory representation:
https://github.com/jump-dev/Xpress.jl/blob/f15573f967a1e4f775e687c87ebf26e397b96118/src/MOI/MOI_wrapper.jl#L3651

**Comment by joaquimg** [comment]
@NLaws did you had the chance to compare .lp's ?

**Comment by NLaws** [comment]
@joaquimg  Sorry no, I have been focused on https://discourse.julialang.org/t/memory-consumption-growth-with-many-large-milps-in-jump/61895 since it is taking down our public API more than once/week

**Comment by joaquimg** [comment]
I have tried this:
```julia
using JuMP, Xpress

for _ in range(1,stop=50000)
    m = Model(()->Xpress.Optimizer(OUTPUTLOG=0))
    @variable(m, x[1:500] >= 0)
    @constraint(m, ctr[1:200], sum(x[i] for i in 1:500) >= 0)
    @objective(m, Min, x[1])
    optimize!(m)
    finalize(m)
end
```

It works very smoothly.

Do you set any parameters or logging in `run_reopt(m, "outage.json")` ?

**Comment by joaquimg** [comment]
Also,
@NLaws , which Julia version you are using?

**Comment by NLaws** [comment]
I am using 1.6.1 and I am not setting any parameters or logging in `run_reopt`.

I think that this issue requires a MILP and branch & bound. So I tried running
```julia
function knapsack(model, M, N, i)
    @variable(model, 0 <= x[1:N] <= 1, Bin)
    @objective(model, Max, rand(N)' * x)
    for i in 1:M
        w = rand(N)
        @constraint(model, w' * x <= N * rand())
    end
    MOI.write_to_file(model, "knapsack$i.milp")
    optimize!(model)
    finalize(model)
end
```
However, the `write_to_file` method does not accept a `Model`? Should I pass `Xpress.Optimizer()`? And if I do that how does `write_to_file` get the constraints etc.?
```julia
ERROR: LoadError: MethodError: no method matching write_to_file(::Model, ::String)
Closest candidates are:
  write_to_file(::Union{MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.FileFormats.MOF.InnerModelFunctionConstraints{Float64}}}, MathOptInterface.Utilities.GenericModel{T, MathOptInterface.FileFormats.CBF.ModelFunctionConstraints{T}} where T, MathOptInterface.Utilities.GenericModel{T, MathOptInterface.FileFormats.LP.ModelScalarConstraints{T, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.ZeroOne}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.Integer}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.EqualTo{T}}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.GreaterThan{T}}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.LessThan{T}}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.ScalarAffineFunction{T}, MathOptInterface.Interval{T}}}} where T, MathOptInterface.Utilities.GenericModel{T, MathOptInterface.FileFormats.MPS.ModelFunctionConstraints{T}} where T, MathOptInterface.Utilities.GenericModel{T, MathOptInterface.FileFormats.SDPA.ModelVectorConstraints{T, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.VectorAffineFunction{T}, MathOptInterface.Nonnegatives}, MathOptInterface.Utilities.VectorOfConstraints{MathOptInterface.VectorAffineFunction{T}, MathOptInterface.PositiveSemidefiniteConeTriangle}}} where T}, ::String) at /Users/nlaws/.julia/packages/MathOptInterface/YDdD3/src/FileFormats/FileFormats.jl:93
  write_to_file(::Xpress.Optimizer, ::String) at /Users/nlaws/.julia/packages/Xpress/r6dU3/src/MOI/MOI_wrapper.jl:3683
```

Also, should I use the .mps file extension?

**Comment by joaquimg** [comment]
the file writing thing was to debug determinism. lets keep that on hold.

**Comment by joaquimg** [comment]
This is working smoothly
```julia

using JuMP, Xpress, Random

function knapsack(model, M=100, N=100, j=0)
    @variable(model, 0 <= x[1:N] <= 1, Bin)
    @objective(model, Max, rand(N)' * x)
    for i in 1:M
        w = rand(N)
        @constraint(model, w' * x <= N * rand())
    end
    # MOI.write_to_file(model, "knapsack$i.milp")
    optimize!(model)
    finalize(model)
end

Random.seed!(1234)
for j in range(1,stop=50000)
    if mod(j,10) == 0
        @show j
    end
    model = Model(()->Xpress.Optimizer(OUTPUTLOG=0))
    knapsack(model)
end
```

**Comment by NLaws** [comment]
Ok I am running it with the original code (in my first post) again. I did a `Pkg.up()` so maybe there was an issue in an older version. 

I am still seeing the memory usage grow with iterations. Are you seeing that with the `knapsack` problem that you are running?

**Comment by joaquimg** [comment]
In `knapsack`,

I see no memory usage growth. My memory varies between 300 and 330mb, constantly going back to 300.

I am on windows, looking at the task manager.

I am on:
```julia
  [4076af6c] JuMP v0.21.8
  [9e70acf3] Xpress v0.12.3
```
and
```
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

**Comment by joaquimg** [comment]
Running on my WSL (virtual machine for Linux):
```
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

Things go very different...

In the first iterations I ha 600mb of RES mem

it gets very fast to 1000mb.
then it seems to grow (slowly, sometimes going down a bit, but overall its growing).

**Comment by joaquimg** [comment]
Interesting, even with:

```
function knapsack(model, M=100, N=100, j=0)
    @variable(model, 0 <= x[1:N] <= 1, Bin)
    @objective(model, Max, rand(N)' * x)
    for i in 1:M
        w = rand(N)
        @constraint(model, w' * x <= N * rand())
    end
    # MOI.write_to_file(model, "knapsack$j.milp")
    optimize!(model)
    finalize(model)
    GC.gc()
end
```

things grow (not as fast though).

**Comment by joaquimg** [comment]
there is almost no growth with:
`model = Model(()->Xpress.Optimizer(OUTPUTLOG=0, THREADS = 1))`

**Comment by NLaws** [comment]
@joaquimg my experience on Mac OS and Linux has been the same as your Linux experience. (I have not tested on Windows).

**Comment by NLaws** [comment]
I cannot recreate the issue now. I ran the original code twice:
```
for _ in range(1,stop=500)
    m = Model(Xpress.Optimizer)
    r = run_reopt(m, "outage.json")
    finalize(m)
end
```
My only guess is that running `Pkg.up()` pulled in a fix.
So closing this issue. I'll come back to it if I see this error pop up again.
