### ISSUE TITLE
Xpress returns pre-solve problem when MAXTIME is reached

### ISSUE THREAD

**Issue by sourabhdalvi** [jump-dev/Xpress.jl#133]
Hi guys,
I'm experiencing this issue where if the solver reaches the MAXTIME passed by the user, Xpress returns the problem in its pre-solved state and if I try to change the RHS of a constraint using ParameterJuMP it throws this error 
```
XpressError(32): Subroutine not completed successfully, possibly due to invalid argument. Unable to call `Xpress.chgrhs`:
402 Error: Invalid row number passed to XPRSchgrhs.
```
Seems like this is default behavior of Xpress, and we need to use  ` XPRSpostsolve` function  to get back the original
problem.  Any help on this is appreciated.
Found a similar issue raised in the Xpress forums [here.](https://community.fico.com/s/question/0D52E000064qY46SAE/after-solving-a-mip-with-an-early-termination-condition-on-time-maxtime-i-change-the-rhs-of-a-set-of-constraints-and-get-the-following-error-solvererror-402-error-invalid-row-number-passed-to-xprschgrhs) 

EDIT : Adding a MWE for anyone who wants to replicate the issue 
```julia
using JuMP, Xpress, PowerSimulations, PowerSystems, PowerSystemCaseBuilder, InfrastructureSystems
const PSI = PowerSimulations
const PSY = PowerSystems
const PSB = PowerSystemCaseBuilder

test_sys = PSB.build_system(PSITestSystems, "modified_RTS_GMLC_DA_sys");
template = template_unit_commitment(network=CopperPlatePowerModel);

solver = JuMP.optimizer_with_attributes(Xpress.Optimizer, "MIPRELSTOP" => 1e-5, "MAXTIME" => 15)
UC = OperationsProblem(
    template,
    test_sys;
    optimizer = solver,
    optimizer_log_print = true,
    balance_slack_variables = true,
)


problems = SimulationProblems(
    UC = UC,
)

sequence = SimulationSequence(
    problems = problems,
    intervals = Dict(
        "UC" => (Hour(24), Consecutive()),
    ),
    ini_cond_chronology = IntraProblemChronology(),
);

sim = Simulation(
    name = "test",
    steps = 2,
    problems = problems,
    sequence = sequence,
    simulation_folder = mktempdir(cleanup = true),
)
build_out = build!(sim; serialize = false)
execute_out = execute!(sim)
```

**Comment by odow** [comment]
That's a pretty painful API design by Xpress... 

Looks like @joaquimg is aware of the issue. Not sure why this is commented:
https://github.com/jump-dev/Xpress.jl/blob/2bdc9b796aeccc130102ed7caaa37668e01a9c9d/src/MOI/MOI_wrapper.jl#L2351-L2364

**Comment by joaquimg** [comment]
1 - Quickest fix to test the rest of you program: disable PRESOLVE
2 - It it always a good idea to ping Xpress support and let them know you are using julia API.
3 - try replacing the comments by this:
```julia
@show state = getintattrib(model.inner, Lib.XPRS_PRESOLVESTATE)
# Bit Meaning
# 0 Problem has been loaded.
# 1 Problem has been LP presolved.
# 2 Problem has been MIP presolved.
# 7 Solution in memory is valid.
@show str = bitstring(Int32(state))
# @show is_loaded = str[end] == '1'
@show is_lppres = str[end-1] == '1'
@show is_mippre = str[end-2] == '1'
# @show is_solava = str[end-7] == '1'
if is_lppres || is_mippre # or just use `is_solava` # dont know what is better
    Xpress.postsolve(model.inner) # - post solve fails is problem is post solved
end
```

**Comment by odow** [comment]
Bitwise `&`? Haha
```julia
state = getintattrib(model.inner, Lib.XPRS_PRESOLVESTATE)
# Bit Meaning
# 0 Problem has been loaded.
# 1 Problem has been LP presolved.
# 2 Problem has been MIP presolved.
# 7 Solution in memory is valid.
is_lppres = state & 2^1 > 0
is_mippre = state & 2^2 > 0
is_solava = state & 2^7 > 0
```

**Comment by sourabhdalvi** [comment]
So, I tried both @joaquimg and @odow  suggested  changes to the commented code, but it still fails if PRESOLVE is not disabled.  With PRESOLVE disabled Xpress returns the original problem and ParameterJuMP works.

**Comment by joaquimg** [comment]
That is weird.
Might be good to check with FICO support and forward the solution here. Disabling presolve should not be long the long term solution.
Whenever you contact them, it is important to highlight that you are using julia. So they can update their understanding of user base.

**Comment by sourabhdalvi** [comment]
@joaquimg I was able to get Xpress to work without disabling PRESOLVE, using @odow suggested changes. It was a  error on my part while initial testing it. I'll post a PR with the changes and close this issue.
