### ISSUE TITLE
When postsolve should be called? (Related to Xpress error 707.)

### ISSUE THREAD

**Issue by henriquebecker91** [jump-dev/Xpress.jl#150]
Issue started by the discussions in this conversation: https://github.com/jump-dev/Xpress.jl/pull/148#discussion_r720376894

Basically, if you set both MIPPRESOLVE and PRESOLVE to zero and MAXNODES to 1, and the problem is hard enough to not be solved in the first node, then calling `optimize!`, setting a primal start, and then calling `optimize!` again will trigger error 707 ("707 Error: Function cannot be called during the global search, except in callbacks."). The error can avoided by calling `postsolve` after the first `optimize!` and before `addmipsol` is called internally. However, the model should not be in presolved state, as both flags mentioned at the start are set to zero. It seems like interrupting the solver may leave it in a "presolved state" even if no presolve was actually done. More evidence on this is that querying `Xpress.Lib.XPRS_PRESOLVESTATE` will indicate no presolve and a solution in memory, but without calling `postsolve` before `addmipsol` the error 707 is triggered.

The MWE can be found in the primal start test in `test/MathOptInterface/MOI_Wrapper.jl`

**Comment by joaquimg** [comment]
closed by #157
