### ISSUE TITLE
Some raw parameters are not recognized, for example: HEUREMPHASIS

### ISSUE THREAD

**Issue by henriquebecker91** [jump-dev/Xpress.jl#154]
I think the last version of Xpress (8.12.0) may have introduced new parameters that Xpress.jl was not updated to recognize yet.
For example, trying to set `HEUREMPHASIS` as a raw parameter will give an error, but the parameter exists. 
Is there some automated procedure to run over one of the Xpress `.h` files that will generate the list of constants? This is probably something that should not be done manually. I have the most recent `.h` file downloaded and could do this if it is somewhat automated.

I just lost a 48h experiment run because before a last MIP solve I tried to set this parameter and the program was killed. I was using an Xpress version that supported it, so I was not really expecting this. Maybe it would be interesting to have a switch that make this kind of error just a warning ("Warn: parameter $PARAM not recognized and not set"), or a macro that could check during compile time the parameter (when it is given as a literal string).

For reference, the code of HEUREMPHASIS is 8427.

**Comment by henriquebecker91** [comment]
Found the script. Created the PR #155 to take care of this, but I am not sure that I will actually finish it, I will probably leave it for someone else finish; I just put the first brick there.

**Comment by joaquimg** [comment]
closed by #155
