### ISSUE TITLE
Setting license file separately from Xpress installation?

### ISSUE THREAD

**Issue by matbesancon** [jump-dev/Xpress.jl#182]
I have a license file separate from XPRESSDIR, the wrapper seems to pick up the license file in the directory by default, is there a way to force it to take another file (not in `XPRESSDIR`)?

**Comment by joaquimg** [comment]
did you try setting `XPAUTH_PATH` ?

**Comment by matbesancon** [comment]
yes and the XPAUTH_PATH seems ignored, with the XPRESSDIR path being taken instead

**Comment by joaquimg** [comment]
Can you report the complete error?
The MW is probably just `using Xpress`. there is something else?
You see here: https://github.com/jump-dev/Xpress.jl/blob/be5e6f3eee2bf2dbc832d9cd2a678c4a587c1392/src/license.jl#L15 that XPAUTH_PATH has priority for the wrapper.
Xpress itself has its own internal rules that are not especially clear in the manual.
If I remember correctly, if you have a lic file in the XPRESSDIR folder, it will try using it anyway. If that is the case, rename that file.

**Comment by matbesancon** [comment]
> If I remember correctly, if you have a lic file in the XPRESSDIR folder, it will try using it anyway

that's exactly the case yes. OK I'll try renaming the file

The MWE would be:
```julia
import Xpress
const MOI = Xpress.MOI
MOI.add_variables(Xpress.Optimizer(), 6000)
```
since the development version allows up to 5000 columns

**Comment by matbesancon** [comment]
perfect I managed to fix it with the file inside express symlinked to what I had as XPAUTH_PATH.

Can be worth a warning in the README?
