### ISSUE TITLE
Unrecognized control parameter.

### ISSUE THREAD

**Issue by mbataillou** [jump-dev/Xpress.jl#272]
I found parameters `MCFCUTSTRATEGY`, and `HEURSHIFTPROP` are not recognised. Those are new parameters from the Xpress 9.4 release.

**Comment by odow** [comment]
Yes, we likely need to update 
https://github.com/jump-dev/Xpress.jl/blob/master/src/Lib/xprs.jl
with any new parameters.

**Comment by mbataillou** [comment]
Create this [PR](https://github.com/jump-dev/Xpress.jl/pull/273) to update the parameters.
