### ISSUE TITLE
Problems finding license on Windows

### ISSUE THREAD

**Issue by trulsf** [jump-dev/Xpress.jl#275]
With the recent version (0.17.0) there is a problem detecting the license file with a standard installation for Windows (not using the Xpress_jll). The environment variable XPRESSDIR will by default be set to the folder of the installation (e.g 'c:\xpressmp') while the license file resides in the 'bin' folder ('c:\xpressmp\bin'). 

I guess this could be added as one of the candidate locations of the license checking in 'license.jl'. The specific check for Windows based on the use of `libdir` does not work as the value is empty ("").

**Comment by odow** [comment]
Okay. Looks like we can just add a new line after
https://github.com/jump-dev/Xpress.jl/blob/c885d034f626d80c47bcd08980e35e973c93d8a0/src/license.jl#L24-L26

**Comment by jd-lara** [comment]
same is happening in Mac

**Comment by odow** [comment]
I'll fix this now

**Comment by odow** [comment]
Can you try #276?
