### ISSUE TITLE
README and presolve

### ISSUE THREAD

**Issue by trulsf** [jump-dev/Xpress.jl#279]
In the README file it it is stated: To use Xpress with JuMP, use:
```
using JuMP, Xpress
model = Model(Xpress.Optimizer)
set_optimizer(model, "PRESOLVE", 0)
```
I guess, it should be `set_attribute(model, "PRESOLVE", 0)`, but the question is: Is it recommended to turn off presolve as a default for Xpress? What features of JuMP will require this (if any)?

**Comment by odow** [comment]
Fixed by https://github.com/jump-dev/Xpress.jl/pull/280.

The `PRESOLVE` was just an example. It's not required or recommended. I've clarified that it is just an example.
