### ISSUE TITLE
Use dispatch in add single variable constraint

### ISSUE THREAD

**Issue by joaquimg** [jump-dev/Xpress.jl#70]

**Comment by guilhermebodin** [comment]
Can we close this? SingleVariable does not exist anymore in the current MOI versions.

**Comment by odow** [comment]
Closing. This is okay:
https://github.com/jump-dev/Xpress.jl/blob/b5bc1e7f0ced3a3bef3b0c7f5a7d0606179c58b6/src/MOI/MOI_wrapper.jl#L1411-L1452

**Comment by joaquimg** [comment]
For future note.
We are not closing because single variable does not exist.
The issue is the same but for variable index.
We are closing because it does not seem to be a bottleneck. Although it seems to be against the julia manual performance tips.
