### ISSUE TITLE
Memory consumption growth in single Julia session

### ISSUE THREAD

**Issue by NLaws** [jump-dev/Xpress.jl#92]
Repeated creation of a JuMP model with an Xpress optimizer, building, and solving the model, appears to lead to indefinite memory growth for the Julia process. The pattern that is repeated in a Julia session is:
```
using JuMP, Xpress
m = Model(Xpress.Optimizer)
```
then building a solving the model with (for example)
```
using REoptLite
results = run_reopt(m, "path/to/scenario.json")
```
The larger the model the larger the memory consumption with ever iteration of the pattern. For example, the julia session may start with about 0.5 GB of memory, then after one run the memory consumption might grow to 1 GB (or more depending on the problem size). Then, on the second iteration (creating a new model - reusing the `m` variable) after the model has solved the memory consumption will grow to 1.5 GB (after spiking to something higher during the solve).  We have seen this pattern lead to the entire RAM available being consumed, leading to the operating system's out-of-memory killer stopping the optimization process. (As a work-around we are currently restarting the Julia sessions periodically).

**Comment by odow** [comment]
Presumably related to this comment
https://github.com/jump-dev/Xpress.jl/blob/b241a855c2c1abe2086b5fb575917b456c441c54/src/MOI/MOI_wrapper.jl#L290-L296

**Comment by NLaws** [comment]
@kdheepak does the above comment ring a bell? Any ideas on what we might change to address this issue?

**Comment by joaquimg** [comment]
I can reproduce with:
```julia

function build_mod3()
    Model(Xpress.Optimizer)
    nothing
end
for i in 1:10_000
    @assert nothing === build_mod3()
end
```
certainly has to do with that comment.

**Comment by joaquimg** [comment]
it was almost ta typo, we were calling `finalize` instead of `finalizer`

**Comment by kdheepak** [comment]
Wow nice find! My bad, I didn't realize there were two things!

**Comment by joaquimg** [comment]
Me neither XD

**Comment by NLaws** [comment]
@joaquimg is it possible that this is also an issue in CPLEX.jl ? I see `finalize` in https://github.com/jump-dev/CPLEX.jl/blob/7019ca7035552cdb4d38c762641fc9fa6c05e5da/test/MathOptInterface/MOI_wrapper.jl but they appear to be tests?  I am seeing the memory consumption problem using CPLEX.jl but I'm not 100% it is the same cause.

**Comment by odow** [comment]
It's not the same problem: https://github.com/jump-dev/CPLEX.jl/blob/71e64ea78fea5dc83c556ee76df2b5ea1df124e4/src/MOI/MOI_wrapper.jl#L225. Open an issue in CPLEX.jl with a reproducible example.
